// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWBWOX-ytVO59GOdOtoP57FU3Qcwn19mY',
    appId: '1:650909675035:web:631f4e0a8b9c29d6a592be',
    messagingSenderId: '650909675035',
    projectId: 'track-that-money-7301b',
    authDomain: 'track-that-money-7301b.firebaseapp.com',
    storageBucket: 'track-that-money-7301b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjiLvqhJdxPfcvZhqIT9BNI9V7wwd87YQ',
    appId: '1:650909675035:android:617845d6bab63030a592be',
    messagingSenderId: '650909675035',
    projectId: 'track-that-money-7301b',
    storageBucket: 'track-that-money-7301b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJAcA55cR3_VJH9RxOcmhxQhRpLRI5-j4',
    appId: '1:650909675035:ios:7a1d0257400528cda592be',
    messagingSenderId: '650909675035',
    projectId: 'track-that-money-7301b',
    storageBucket: 'track-that-money-7301b.firebasestorage.app',
    iosBundleId: 'com.example.trackThatMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJAcA55cR3_VJH9RxOcmhxQhRpLRI5-j4',
    appId: '1:650909675035:ios:7a1d0257400528cda592be',
    messagingSenderId: '650909675035',
    projectId: 'track-that-money-7301b',
    storageBucket: 'track-that-money-7301b.firebasestorage.app',
    iosBundleId: 'com.example.trackThatMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWBWOX-ytVO59GOdOtoP57FU3Qcwn19mY',
    appId: '1:650909675035:web:99a179292a14a3dea592be',
    messagingSenderId: '650909675035',
    projectId: 'track-that-money-7301b',
    authDomain: 'track-that-money-7301b.firebaseapp.com',
    storageBucket: 'track-that-money-7301b.firebasestorage.app',
  );
}
